const movieCollection = [
  {
    id: 1,
    title: "Shadows of Neo-Tokyo",
    epilogue: "In a rain-soaked future, a detective hunts a ghost in the machine.",
    dateReleased: "2024-05-12",
    category: "Sci-Fi",
    type: "Feature Film",
    actors: ["Kenji Sato", "Elena Vance"],
    trailer: "https://youtube.com/watch?v=neotokyo-trailer",
    rating: 8.5,
    keywords: ["cyberpunk", "future", "mystery"],
    kind: "R",
    image: "https://images.unsplash.com/photo-1605806616949-1e87b487fc2f?q=80&w=1000"
  },
  {
    id: 2,
    title: "The Last Summit",
    epilogue: "Two estranged brothers attempt to climb the world's most dangerous peak.",
    dateReleased: "2023-11-20",
    category: "Drama",
    type: "Feature Film",
    actors: ["Liam Neeson", "Tom Hardy"],
    trailer: "https://youtube.com/watch?v=summit-climb",
    rating: 7.9,
    keywords: ["mountain", "survival", "family"],
    kind: "PG-13",
    image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=80&w=1000"
  },
  {
    id: 3,
    title: "Laughter in the Rain",
    epilogue: "A chance encounter at a bus stop leads to a decade of friendship and missed connections.",
    dateReleased: "2025-02-14",
    category: "Romance",
    type: "Feature Film",
    actors: ["Emma Stone", "Timothée Chalamet"],
    trailer: "https://youtube.com/watch?v=rainy-romance",
    rating: 8.2,
    keywords: ["love", "destiny", "city-life"],
    kind: "PG",
    image: "https://images.unsplash.com/photo-1511317558624-0414033c39cc?q=80&w=1000"
  },
  {
    id: 4,
    title: "The Coral Ghost",
    epilogue: "A deep-dive look into the vanishing reefs of the South Pacific.",
    dateReleased: "2024-08-01",
    category: "Nature",
    type: "Documentary",
    actors: ["David Attenborough (Narrator)"],
    trailer: "https://youtube.com/watch?v=coral-reef-doc",
    rating: 9.1,
    keywords: ["ocean", "environment", "nature"],
    kind: "G",
    image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=1000"
  },
  {
    id: 5,
    title: "Velocity",
    epilogue: "An underground street racer is forced into a high-stakes heist.",
    dateReleased: "2024-03-10",
    category: "Action",
    type: "Feature Film",
    actors: ["Vin Diesel", "Michelle Rodriguez"],
    trailer: "https://youtube.com/watch?v=velocity-cars",
    rating: 6.8,
    keywords: ["cars", "racing", "crime"],
    kind: "PG-13",
    image: "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?q=80&w=1000"
  },
  {
    id: 6,
    title: "Kitchen Nightmares: Paris",
    epilogue: "A failing bistro in the heart of Paris gets a second chance.",
    dateReleased: "2023-09-15",
    category: "Drama",
    type: "Short Film",
    actors: ["Léa Seydoux"],
    trailer: "https://youtube.com/watch?v=chef-paris",
    rating: 7.4,
    keywords: ["cooking", "paris", "passion"],
    kind: "PG",
    image: "https://images.unsplash.com/photo-1556910103-1c02745aae4d?q=80&w=1000"
  },
  {
    id: 7,
    title: "The Midnight Gallery",
    epilogue: "Paintings come to life after the museum doors lock at midnight.",
    dateReleased: "2025-10-31",
    category: "Horror",
    type: "Feature Film",
    actors: ["Anya Taylor-Joy"],
    trailer: "https://youtube.com/watch?v=midnight-art",
    rating: 7.1,
    keywords: ["museum", "ghosts", "art"],
    kind: "R",
    image: "https://images.unsplash.com/photo-1518998053901-5348d3961a04?q=80&w=1000"
  },
  {
    id: 8,
    title: "Mars Colony One",
    epilogue: "The first humans on Mars face an unexpected technical catastrophe.",
    dateReleased: "2026-01-01",
    category: "Sci-Fi",
    type: "Feature Film",
    actors: ["Matt Damon", "Jessica Chastain"],
    trailer: "https://youtube.com/watch?v=mars-one",
    rating: 8.7,
    keywords: ["space", "mars", "survival"],
    kind: "PG-13",
    image: "https://images.unsplash.com/photo-1614728894747-a83421e2b9c9?q=80&w=1000"
  },
  {
    id: 9,
    title: "The Jazz Man",
    epilogue: "The life and times of a forgotten trumpet player in 1950s New Orleans.",
    dateReleased: "2023-12-25",
    category: "Musical",
    type: "Feature Film",
    actors: ["Mahershala Ali"],
    trailer: "https://youtube.com/watch?v=jazz-trumpet",
    rating: 8.9,
    keywords: ["jazz", "music", "history"],
    kind: "PG-13",
    image: "https://images.unsplash.com/photo-1511192336575-5a79af67a629?q=80&w=1000"
  },
  {
    id: 10,
    title: "Under the Neon Sun",
    epilogue: "A vibrant comedy about three friends traveling through Florida.",
    dateReleased: "2024-07-04",
    category: "Comedy",
    type: "Feature Film",
    actors: ["Seth Rogen", "Bill Hader"],
    trailer: "https://youtube.com/watch?v=neon-sun-trip",
    rating: 6.5,
    keywords: ["road-trip", "florida", "friends"],
    kind: "R",
    image: "https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?q=80&w=1000"
  },
  {
    id: 11,
    title: "Concrete Jungle",
    epilogue: "An exploration of urban wildlife living in New York City.",
    dateReleased: "2024-04-22",
    category: "Nature",
    type: "Documentary",
    actors: ["Sigourney Weaver (Narrator)"],
    trailer: "https://youtube.com/watch?v=nyc-animals",
    rating: 8.0,
    keywords: ["city", "animals", "environment"],
    kind: "G",
    image: "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?q=80&w=1000"
  },
  {
    id: 12,
    title: "The Alchemist",
    epilogue: "A young boy discovers he can turn base metals into gold, but at a cost.",
    dateReleased: "2025-11-12",
    category: "Fantasy",
    type: "Feature Film",
    actors: ["Dev Patel", "Tilda Swinton"],
    trailer: "https://youtube.com/watch?v=alchemist-gold",
    rating: 8.4,
    keywords: ["magic", "greed", "ancient"],
    kind: "PG-13",
    image: "https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=1000"
  },
  {
    id: 13,
    title: "Silent Witness",
    epilogue: "A deaf woman witnesses a crime through her apartment window.",
    dateReleased: "2024-02-09",
    category: "Thriller",
    type: "Feature Film",
    actors: ["Millicent Simmonds"],
    trailer: "https://youtube.com/watch?v=silent-crime",
    rating: 7.8,
    keywords: ["suspense", "crime", "urban"],
    kind: "R",
    image: "https://images.unsplash.com/photo-1485872222694-8974a214993c?q=80&w=1000"
  },
  {
    id: 14,
    title: "Retrograde",
    epilogue: "Time starts moving backward for one man on his 40th birthday.",
    dateReleased: "2025-06-20",
    category: "Sci-Fi",
    type: "Short Film",
    actors: ["Oscar Isaac"],
    trailer: "https://youtube.com/watch?v=time-backwards",
    rating: 8.3,
    keywords: ["time", "surreal", "paradox"],
    kind: "PG",
    image: "https://images.unsplash.com/photo-1501139083538-0139583c060f?q=80&w=1000"
  },
  {
    id: 15,
    title: "The Great Heist",
    epilogue: "A group of retirees plans to rob the bank that lost their pensions.",
    dateReleased: "2023-10-10",
    category: "Comedy",
    type: "Feature Film",
    actors: ["Morgan Freeman", "Michael Caine", "Alan Arkin"],
    trailer: "https://youtube.com/watch?v=pension-robbery",
    rating: 7.2,
    keywords: ["heist", "funny", "justice"],
    kind: "PG-13",
    image: "https://images.unsplash.com/photo-1501167786227-4cba60f6d58f?q=80&w=1000"
  },
  {
    id: 16,
    title: "Ocean's Breath",
    epilogue: "Capturing the beauty of free-diving in the Mediterranean.",
    dateReleased: "2024-05-30",
    category: "Sports",
    type: "Documentary",
    actors: ["Guillaume Néry"],
    trailer: "https://youtube.com/watch?v=freedive-med",
    rating: 9.0,
    keywords: ["diving", "ocean", "peace"],
    kind: "G",
    image: "https://images.unsplash.com/photo-1518467166778-b88f373ffec7?q=80&w=1000"
  },
  {
    id: 17,
    title: "Robot & Me",
    epilogue: "An AI companion helps a lonely senior navigate modern life.",
    dateReleased: "2025-01-15",
    category: "Drama",
    type: "Feature Film",
    actors: ["Anthony Hopkins"],
    trailer: "https://youtube.com/watch?v=robot-friend",
    rating: 8.6,
    keywords: ["AI", "future", "emotions"],
    kind: "PG",
    image: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?q=80&w=1000"
  },
  {
    id: 18,
    title: "The Haunting of Hill House",
    epilogue: "A family confronts memories of their old home and the terrors within.",
    dateReleased: "2023-10-31",
    category: "Horror",
    type: "Feature Film",
    actors: ["Victoria Pedretti"],
    trailer: "https://youtube.com/watch?v=ghost-house",
    rating: 8.1,
    keywords: ["scary", "family", "ghosts"],
    kind: "R",
    image: "https://images.unsplash.com/photo-1505635330303-31953027484d?q=80&w=1000"
  },
  {
    id: 19,
    title: "Stellar Journey",
    epilogue: "The search for a new Earth begins in a distant star system.",
    dateReleased: "2026-07-20",
    category: "Sci-Fi",
    type: "Feature Film",
    actors: ["Matthew McConaughey"],
    trailer: "https://youtube.com/watch?v=stellar-travel",
    rating: 8.8,
    keywords: ["stars", "galaxy", "exploration"],
    kind: "PG-13",
    image: "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?q=80&w=1000"
  },
  {
    id: 20,
    title: "The Winter King",
    epilogue: "A historical epic about the rise of a young king in a frozen land.",
    dateReleased: "2024-12-01",
    category: "History",
    type: "Feature Film",
    actors: ["Alexander Skarsgård"],
    trailer: "https://youtube.com/watch?v=winter-king-war",
    rating: 7.7,
    keywords: ["snow", "king", "war"],
    kind: "R",
    image: "https://images.unsplash.com/photo-1507187632231-5beb21a65d12?q=80&w=1000"
  }
];

export default movieCollection;